#!/usr/bin/env bash
# Prepare ONE HTCondor worker for fedcast cross-silo runs.
#
#   sudo tools/silo_worker_setup.sh KTLX[,KVNX...] [DATA_DIR] [ATTRIBUTE]
#   sudo tools/silo_worker_setup.sh none           [DATA_DIR] [ATTRIBUTE]
#
# YOU USUALLY DO NOT NEED THIS. The defaults in silos.example.yml — pinning
# by `machine:` and a home-relative data_dir — require no worker
# configuration at all: HTCondor already knows every machine's name, the
# shard directory is inside Apptainer's default mounts so nothing is
# bind-mounted, and the preprocess job creates the directory itself.
#
# Run this only when the silo map departs from those defaults:
#
#   - data_dir is an absolute path outside ~/, /tmp/ or /var/tmp/. It is
#     then bind-mounted into the containers POOL-WIDE, and Apptainer
#     refuses to start when a bind source is missing — so RUN THIS ON EVERY
#     WORKER, passing `none` on the ones that hold no data.
#   - silos are pinned by advertised ClassAd (`{}` entries) instead of by
#     machine name. Run it on each data holder with the silos it hosts.
#
# On a data holder, pass the silos it hosts. The script:
#   - creates DATA_DIR with one subdirectory per hosted silo;
#   - advertises the hosted silos in the ClassAd ATTRIBUTE (default
#     FEDCAST_SILOS), which is what pins each client's jobs here;
#   - advertises DATA_DIR in FEDCAST_SILO_DIR so tools/silo_check.py can
#     confirm every worker can satisfy the bind.
#
# Match DATA_DIR / ATTRIBUTE to the values in your silos.yml. Re-run to
# change the hosted set; the config snippet is overwritten.
set -euo pipefail

SILOS=${1:?usage: $0 SILO[,SILO...]|none [DATA_DIR] [ATTRIBUTE]}
DATA_DIR=${2:-/var/lib/fedcast/silos}
ATTR=${3:-FEDCAST_SILOS}

if [ "$(id -u)" -ne 0 ]; then
    echo "run as root (sudo): needs to write $DATA_DIR and /etc/condor/config.d" >&2
    exit 1
fi

# Jobs run as the pool's job user (often not root); a sticky world-writable
# root lets each preprocess job create and refill its own silo directory.
install -d -m 1777 "$DATA_DIR"

HOSTED=""
if [ "$SILOS" != "none" ] && [ "$SILOS" != "-" ]; then
    HOSTED=$SILOS
    IFS=',' read -r -a LIST <<< "$SILOS"
    for s in "${LIST[@]}"; do
        install -d -m 0777 "$DATA_DIR/$s"
    done
fi

CONF_D=/etc/condor/config.d
if [ ! -d "$CONF_D" ]; then
    echo "$CONF_D not found — is this an HTCondor worker?" >&2
    exit 1
fi
SNIPPET="$CONF_D/60-fedcast-silo.config"
cat > "$SNIPPET" <<CFG
# Generated by fedcast-workflow tools/silo_worker_setup.sh
$ATTR = "$HOSTED"
FEDCAST_SILO_DIR = "$DATA_DIR"
STARTD_ATTRS = \$(STARTD_ATTRS) $ATTR FEDCAST_SILO_DIR
CFG
condor_reconfig >/dev/null 2>&1 || condor_reconfig -startd

if [ -n "$HOSTED" ]; then
    echo "silo worker ready — hosts: $HOSTED"
else
    echo "worker ready — hosts no silo (bind directory only)"
fi
echo "  data dir : $DATA_DIR"
echo "  ClassAds : $ATTR=\"$HOSTED\"  FEDCAST_SILO_DIR=\"$DATA_DIR\"  ($SNIPPET)"
echo "verify from the submit host:  tools/silo_check.py silos.yml"
